### ISSUE TITLE
No member named IsConnected

### ISSUE THREAD

**Issue by microcosm** [anagma/ofxNetworkSync#1]
Hi,

I tried this in 0.8.4 and 0.9.2. In both when running the server example or the auto example I get the same compile error:

```
No member named 'IsConnected' in 'ofxUDPManager'
```

**Comment by microcosm** [comment]
Lines 77 and 81 of ofxNetworkSyncServerFinder.h

**Comment by anagma** [comment]
Thanks for your reporting microcosm.
before i'd hacked ofxUDPManager and commit hacked ver.
I fixed it. please check it.

**Comment by microcosm** [comment]
Hey, I checked. It works perfectly - thanks!
