### ISSUE TITLE
Redundant code?

### ISSUE THREAD

**Issue by microcosm** [anagma/ofxNetworkSync#2]
Is there a reason in [ofSoundPlayerDelayed.h](https://github.com/anagma/ofxNetworkSync/blob/master/ofxNetworkSyncAutoNetworkExample/src/ofSoundPlayerDelayed.h) you add `ofGetElapsedTimeMillis()`...

``` cpp
playTime = ofGetElapsedTimeMillis()+delay;
startThread(true);
```

... only to immediately subtract it again afterwards?

``` cpp
int delay = playTime - ofGetElapsedTimeMillis();
ofSleepMillis(delay);
```

Does this actually help the syncing? I can't imagine much time is passing as a result of that one `startThread(true)` call?

**Comment by anagma** [comment]
yeah, it is no reason. i just wrote as that. i simplified it. thx!
